version: "3.8"
services:
  astro:
    build:
      context: ./astro
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./astro:/app
      - astro_node_modules:/app/node_modules
    env_file:
      - config/astro/.env
    depends_on:
      - postgres
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  astro_node_modules:
