import type { Record as IRecord } from "@prisma/client";

export const formattedRecordAchievedDate = (record: IRecord) => {
  const achievedAt = record.achievedAt;
  const isFirstDateOfYear =
    achievedAt.getMonth() === 0 && achievedAt.getDate() === 1;
  return achievedAt.toLocaleDateString("fi", {
    year: "numeric",
    month: isFirstDateOfYear ? undefined : "2-digit",
    day: isFirstDateOfYear ? undefined : "2-digit",
  });
};

export const GENDERS = ["Aikuiset", "Pojat", "Tytöt"] as const;

export type Gender = (typeof GENDERS)[number];

export const LEAGUES = [
  "Miehet",
  "Naiset",
  "Pojat 9",
  "Pojat 10",
  "Pojat 11",
  "Pojat 12",
  "Pojat 13",
  "Pojat 14",
  "Pojat 15",
  "Tytöt 9",
  "Tytöt 10",
  "Tytöt 11",
  "Tytöt 12",
  "Tytöt 13",
  "Tytöt 14",
  "Tytöt 15",
] as const;

export type League = (typeof LEAGUES)[number];

export const EVENTS = [
  "40m",
  "60m",
  "100m",
  "200m",
  "300m",
  "400m",
  "800m",
  "1000m",
  "1500m",
  "2000m",
  "3000m",
  "5000m",
  "10000m",
  "Puolimaraton",
  "Maraton",
  "1500m estejuoksu",
  "3000m estejuoksu",
  "60m aitajuoksu",
  "80m aitajuoksu",
  "100m aitajuoksu",
  "110m aitajuoksu",
  "200m aitajuoksu",
  "300m aitajuoksu",
  "400m aitajuoksu",
  "Korkeus",
  "Seiväs",
  "Pituus",
  "Kolmiloikka",
  "Kuula",
  "Kiekko",
  "Moukari",
  "Keihäs",
  "Kolmiottelu",
  "Neliottelu",
  "Viisiottelu",
  "Seitsenottelu",
  "Kymmenottelu",
  "600m kävely",
  "1000m kävely",
  "2000m kävely",
  "3000m kävely",
  "10km kävely",
  "20km kävely",
  "50km kävely",
] as const;

export type RecordEvent = (typeof EVENTS)[number];

export const LEAGUES_BY_GENDER: Record<Gender, League[]> = {
  Aikuiset: ["Miehet", "Naiset"],
  Pojat: [
    "Pojat 9",
    "Pojat 10",
    "Pojat 11",
    "Pojat 12",
    "Pojat 13",
    "Pojat 14",
    "Pojat 15",
  ],
  Tytöt: [
    "Tytöt 9",
    "Tytöt 10",
    "Tytöt 11",
    "Tytöt 12",
    "Tytöt 13",
    "Tytöt 14",
    "Tytöt 15",
  ],
};

export const EVENTS_BY_LEAGUE: Record<League, RecordEvent[]> = {
  "Pojat 9": [
    "40m",
    "1000m",
    "Korkeus",
    "Pituus",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Kolmiottelu",
    "Neliottelu",
    "600m kävely",
  ],
  "Pojat 10": [
    "60m",
    "1000m",
    "60m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Kolmiottelu",
    "Neliottelu",
    "1000m kävely",
  ],
  "Pojat 11": [
    "60m",
    "1000m",
    "60m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Kolmiottelu",
    "Neliottelu",
    "1000m kävely",
  ],
  "Pojat 12": [
    "60m",
    "200m",
    "1000m",
    "60m aitajuoksu",
    "200m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Neliottelu",
    "Viisiottelu",
    "2000m kävely",
  ],
  "Pojat 13": [
    "60m",
    "200m",
    "1000m",
    "60m aitajuoksu",
    "200m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Neliottelu",
    "Viisiottelu",
    "2000m kävely",
  ],
  "Pojat 14": [
    "100m",
    "300m",
    "800m",
    "2000m",
    "1500m estejuoksu",
    "100m aitajuoksu",
    "300m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Viisiottelu",
    "3000m kävely",
  ],
  "Pojat 15": [
    "100m",
    "300m",
    "800m",
    "2000m",
    "1500m estejuoksu",
    "100m aitajuoksu",
    "300m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Viisiottelu",
    "3000m kävely",
  ],
  "Tytöt 9": [
    "40m",
    "1000m",
    "Korkeus",
    "Pituus",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Kolmiottelu",
    "Neliottelu",
    "600m kävely",
  ],
  "Tytöt 10": [
    "60m",
    "1000m",
    "60m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Kolmiottelu",
    "Neliottelu",
    "1000m kävely",
  ],
  "Tytöt 11": [
    "60m",
    "1000m",
    "60m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Kolmiottelu",
    "Neliottelu",
    "1000m kävely",
  ],
  "Tytöt 12": [
    "60m",
    "200m",
    "1000m",
    "60m aitajuoksu",
    "200m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Neliottelu",
    "Viisiottelu",
    "2000m kävely",
  ],
  "Tytöt 13": [
    "60m",
    "200m",
    "1000m",
    "60m aitajuoksu",
    "200m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Neliottelu",
    "Viisiottelu",
    "2000m kävely",
  ],
  "Tytöt 14": [
    "100m",
    "300m",
    "800m",
    "2000m",
    "1500m estejuoksu",
    "80m aitajuoksu",
    "300m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Viisiottelu",
    "3000m kävely",
  ],
  "Tytöt 15": [
    "100m",
    "300m",
    "800m",
    "2000m",
    "1500m estejuoksu",
    "80m aitajuoksu",
    "300m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Viisiottelu",
    "3000m kävely",
  ],
  Miehet: [
    "100m",
    "200m",
    "400m",
    "800m",
    "1500m",
    "3000m",
    "5000m",
    "10000m",
    "Puolimaraton",
    "Maraton",
    "3000m estejuoksu",
    "110m aitajuoksu",
    "400m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Kymmenottelu",
    "20km kävely",
    "50km kävely",
  ],
  Naiset: [
    "100m",
    "200m",
    "400m",
    "800m",
    "1500m",
    "3000m",
    "5000m",
    "10000m",
    "Puolimaraton",
    "Maraton",
    "3000m estejuoksu",
    "100m aitajuoksu",
    "400m aitajuoksu",
    "Korkeus",
    "Seiväs",
    "Pituus",
    "Kolmiloikka",
    "Kuula",
    "Kiekko",
    "Moukari",
    "Keihäs",
    "Seitsenottelu",
    "10km kävely",
    "20km kävely",
  ],
};
