name: Backup DB
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  Backup-DB:
    runs-on: ubuntu-latest
    steps:
      - uses: tj-actions/pg-dump@v2.3
        with:
          database_url: ${{ secrets.DATABASE_URL }}
          path: db.sql
      - uses: actions/upload-artifact@v4
        with:
          name: DB Backup
          path: db.sql
