name: Send Press Release
on:
  schedule:
    - cron: 0 4 * * 1,4
jobs:
  Send-Press-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@v1
        with:
          url: "https://laitilanjyskeyleisurheilu.fi/api/secret/sendCurrentDatePressRelease"
          customHeaders: '{"Content-Type": "application/json", "Authorization": "${{ secrets.API_SECRET }}"}'
